<?php
/**
 * Author: David Edward England, PhD
 * ORCID: https://orcid.org/0009-0001-2095-6646
 * Repo: https://github.com/DavidEngland/genealogy
 */
/**
 * GEDCOM Biography Quality Ranker
 *
 * Ranks bios for completeness/quality based on GEDCOM notes and core events.
 *
 * Usage:
 *   php scripts/gedcom_bio_quality.php --input GEDs/example.ged --out sources/example-bio-quality.json
 *   php scripts/gedcom_bio_quality.php --input GEDs/example.ged --out-md sources/example-bio-quality.md
 *   php scripts/gedcom_bio_quality.php --input GEDs/example.ged --out-csv sources/example-bio-quality.csv --status needs-work
 *
 * Options:
 *   --input <file.ged>      Input GEDCOM file (required)
 *   --out <file.json>       Output JSON report
 *   --out-md <file.md>      Output Markdown report
 *   --out-csv <file.csv>    Output CSV report
 *   --config <file.json>    Optional scoring config override
 *   --status <status>       Filter by status (ok|review|needs-work)
 *   --min-score <n>         Minimum score threshold
 *   --top <n>               Limit output to top N results after sorting
 *   --sort <asc|desc>       Sort by score (default: asc)
 *   --help                  Show help
 */

declare(strict_types=1);

function usage(): void {
    fwrite(STDERR, "Usage: php scripts/gedcom_bio_quality.php --input <file.ged> [--out <file.json>] [--out-md <file.md>] [--out-csv <file.csv>] [--config <file.json>] [--status ok|review|needs-work] [--min-score <n>] [--top <n>] [--sort asc|desc]\n");
}

$options = getopt('', ['input:', 'out:', 'out-md:', 'out-csv:', 'config:', 'status:', 'min-score:', 'top:', 'sort:', 'help']);
if (isset($options['help'])) {
    usage();
    exit(0);
}

$input = $options['input'] ?? '';
if ($input === '') {
    usage();
    exit(1);
}

if (!file_exists($input)) {
    fwrite(STDERR, "Error: Input file not found: {$input}\n");
    exit(1);
}

$outJson = $options['out'] ?? '';
$outMd = $options['out-md'] ?? '';
$outCsv = $options['out-csv'] ?? '';
$statusFilter = isset($options['status']) ? strtolower(trim((string)$options['status'])) : '';
$minScore = isset($options['min-score']) ? (float)$options['min-score'] : null;
$topN = isset($options['top']) ? max(1, (int)$options['top']) : 0;
$sortDir = isset($options['sort']) ? strtolower(trim((string)$options['sort'])) : 'asc';

$defaultConfig = [
    'weights' => [
        'hasBiography' => 10,
        'hasSources' => 10,
        'hasReferences' => 10,
        'birthDate' => 5,
        'birthPlace' => 5,
        'deathDate' => 5,
        'deathPlace' => 5,
        'hasParents' => 5,
        'hasSpouse' => 5,
        'hasChildren' => 5,
        'noteLength' => [
            ['min' => 800, 'score' => 15],
            ['min' => 300, 'score' => 8],
            ['min' => 120, 'score' => 4],
        ],
        'externalId' => 2,
        'externalIdMax' => 8,
        'hasCategoriesOrTemplates' => 3,
    ],
    'penalties' => [
        ['pattern' => '/auto-generated by a GEDCOM import/i', 'score' => -35, 'flag' => 'auto_generated'],
        ['pattern' => '/rough draft/i', 'score' => -15, 'flag' => 'rough_draft'],
        ['pattern' => '/Needs Sources/i', 'score' => -20, 'flag' => 'needs_sources'],
        ['pattern' => '/GEDCOM import/i', 'score' => -12, 'flag' => 'gedcom_import'],
        ['pattern' => '/Please edit, add, or delete/i', 'score' => -10, 'flag' => 'please_edit'],
        ['pattern' => '/Family Information \(Needs Sources\)/i', 'score' => -12, 'flag' => 'family_info_needs_sources'],
        ['pattern' => '/Family Tradition \(Needs Sources\)/i', 'score' => -12, 'flag' => 'family_tradition_needs_sources'],
    ],
    'thresholds' => [
        'ok' => 70,
        'review' => 40,
    ],
];

function loadConfig(string $path, array $defaultConfig): array {
    if ($path === '' || !file_exists($path)) {
        return $defaultConfig;
    }

    $json = file_get_contents($path);
    $config = json_decode($json, true);
    if (!is_array($config)) {
        fwrite(STDERR, "Warning: Invalid JSON in config file: {$path}. Using defaults.\n");
        return $defaultConfig;
    }

    return array_replace_recursive($defaultConfig, $config);
}

$config = loadConfig($options['config'] ?? '', $defaultConfig);
$weights = $config['weights'] ?? $defaultConfig['weights'];
$penalties = $config['penalties'] ?? $defaultConfig['penalties'];
$thresholds = $config['thresholds'] ?? $defaultConfig['thresholds'];

function extractDatabaseIds(string $text): array {
    $ids = [];

    if (preg_match('/(?:WikiTree|wiki)\/([A-Z][a-z]+-\d+)/i', $text, $m)) {
        $ids['wikitree'] = $m[1];
    }

    if (preg_match('/ark:\/61903\/1:1:([A-Z0-9]{6,})|(?:FamilySearch|FS)[\s:]*([A-Z0-9]{4,})/i', $text, $m)) {
        $ids['familysearch'] = $m[1] ?? $m[2];
    }

    if (preg_match('/(?:ancestry\.com\/trees?|Ancestry)[\s:]*\/?(\d{6,})|Ancestry[\s:]*([0-9]+)/i', $text, $m)) {
        $ids['ancestry'] = $m[1] ?? $m[2];
    }

    if (preg_match('/(?:find[\s-]?a[\s-]?grave|findagrave|FAG)[\s:]*\/?(\d{7,})|findagrave\.com\/cgi-bin\/fg.cgi\?id=(\d+)/i', $text, $m)) {
        $ids['findagrave'] = $m[1] ?? $m[2];
    }

    return $ids;
}

function parseGedcom(array $lines): array {
    $individuals = [];
    $families = [];

    $currentType = null;
    $currentId = null;
    $currentEvent = null;

    foreach ($lines as $line) {
        if (!preg_match('/^(\d+)\s+(?:(@[^@]+@)\s+)?([^\s]+)\s*(.*)$/', $line, $m)) {
            continue;
        }
        $level = (int)$m[1];
        $pointer = $m[2] ?? null;
        $tag = $m[3];
        $value = trim($m[4] ?? '');

        if ($level === 0) {
            $currentEvent = null;
            if ($tag === 'INDI') {
                $currentType = 'INDI';
                $currentId = $pointer;
                $individuals[$currentId] = $individuals[$currentId] ?? [
                    'id' => $currentId,
                    'name' => '',
                    'given' => '',
                    'surname' => '',
                    'sex' => '',
                    'ids' => [],
                    'events' => [],
                    'fams' => [],
                    'famc' => null,
                    'notes' => [],
                    'currentNote' => null,
                ];
            } elseif ($tag === 'FAM') {
                $currentType = 'FAM';
                $currentId = $pointer;
                $families[$currentId] = $families[$currentId] ?? [
                    'id' => $currentId,
                    'husb' => null,
                    'wife' => null,
                    'children' => [],
                    'events' => [],
                ];
            } else {
                $currentType = null;
                $currentId = null;
            }
            continue;
        }

        if ($currentType === 'INDI' && $currentId !== null) {
            if ($level === 1) {
                $currentEvent = null;
                switch ($tag) {
                    case 'NAME':
                        $individuals[$currentId]['name'] = $value;
                        break;
                    case 'GIVN':
                        $individuals[$currentId]['given'] = $value;
                        break;
                    case 'SURN':
                        $individuals[$currentId]['surname'] = $value;
                        break;
                    case 'SEX':
                        $individuals[$currentId]['sex'] = $value;
                        break;
                    case 'FAMS':
                        $individuals[$currentId]['fams'][] = $value;
                        break;
                    case 'FAMC':
                        $individuals[$currentId]['famc'] = $value;
                        break;
                    case 'WWW':
                        $ids = extractDatabaseIds($value);
                        foreach ($ids as $service => $id) {
                            $individuals[$currentId]['ids'][$service] = $id;
                        }
                        break;
                    case 'NOTE':
                        $ids = extractDatabaseIds($value);
                        foreach ($ids as $service => $id) {
                            if (!isset($individuals[$currentId]['ids'][$service])) {
                                $individuals[$currentId]['ids'][$service] = $id;
                            }
                        }
                        $individuals[$currentId]['notes'][] = $value;
                        $individuals[$currentId]['currentNote'] = count($individuals[$currentId]['notes']) - 1;
                        break;
                    case 'BIRT':
                    case 'DEAT':
                    case 'CHR':
                    case 'BURI':
                        $currentEvent = $tag;
                        $individuals[$currentId]['events'][$currentEvent] = $individuals[$currentId]['events'][$currentEvent] ?? ['date' => '', 'place' => ''];
                        break;
                }
            } elseif ($level === 2) {
                if ($currentEvent !== null) {
                    if ($tag === 'DATE') {
                        $individuals[$currentId]['events'][$currentEvent]['date'] = $value;
                    } elseif ($tag === 'PLAC') {
                        $individuals[$currentId]['events'][$currentEvent]['place'] = $value;
                    }
                }
                if (($tag === 'CONT' || $tag === 'CONC') && $individuals[$currentId]['currentNote'] !== null) {
                    $noteIdx = $individuals[$currentId]['currentNote'];
                    $sep = ($tag === 'CONT') ? "\n" : '';
                    $individuals[$currentId]['notes'][$noteIdx] .= $sep . $value;
                }
            }
        } elseif ($currentType === 'FAM' && $currentId !== null) {
            if ($level === 1) {
                $currentEvent = null;
                switch ($tag) {
                    case 'HUSB':
                        $families[$currentId]['husb'] = $value;
                        break;
                    case 'WIFE':
                        $families[$currentId]['wife'] = $value;
                        break;
                    case 'CHIL':
                        $families[$currentId]['children'][] = $value;
                        break;
                    case 'MARR':
                        $currentEvent = 'MARR';
                        $families[$currentId]['events']['MARR'] = $families[$currentId]['events']['MARR'] ?? ['date' => '', 'place' => ''];
                        break;
                }
            } elseif ($level >= 2 && $currentEvent !== null) {
                if ($tag === 'DATE') {
                    $families[$currentId]['events'][$currentEvent]['date'] = $value;
                } elseif ($tag === 'PLAC') {
                    $families[$currentId]['events'][$currentEvent]['place'] = $value;
                }
            }
        }
    }

    return [$individuals, $families];
}

function displayName(array $person): string {
    $given = trim($person['given'] ?? '');
    $surname = trim($person['surname'] ?? '');
    if ($given !== '' && $surname !== '') {
        return $given . ' ' . $surname;
    }
    $name = trim($person['name'] ?? '');
    if ($name !== '') {
        return str_replace('/', '', $name);
    }
    return $person['id'] ?? 'Unknown';
}

function normalizeText(string $text): string {
    $text = preg_replace('/\s+/', ' ', $text);
    return trim($text);
}

function collectNoteText(array $person): string {
    if (empty($person['notes'])) {
        return '';
    }
    return trim(implode("\n\n", $person['notes']));
}

function hasSection(string $text, string $name): bool {
    $pattern = '/==\s*' . preg_quote($name, '/') . '\s*==/i';
    return (bool)preg_match($pattern, $text);
}

function countRefs(string $text): int {
    if ($text === '') return 0;
    preg_match_all('/<ref\b/i', $text, $matches);
    return count($matches[0]);
}

function hasCategoriesOrTemplates(string $text): bool {
    if ($text === '') return false;
    if (preg_match('/\[\[Category:/i', $text)) return true;
    if (preg_match('/\{\{[A-Za-z0-9 _-]+\}\}/', $text)) return true;
    return false;
}

function hasChildren(array $person, array $families): bool {
    foreach ($person['fams'] as $famId) {
        if (!isset($families[$famId])) continue;
        if (!empty($families[$famId]['children'])) return true;
    }
    return false;
}

function applyNoteLengthBonus(int $length, array $rules, array &$reasons): int {
    foreach ($rules as $rule) {
        $min = (int)($rule['min'] ?? 0);
        $score = (int)($rule['score'] ?? 0);
        if ($min > 0 && $length >= $min) {
            $reasons[] = "note_length>=${min}(+${score})";
            return $score;
        }
    }
    return 0;
}

function detectPenalties(string $text, array $penalties, array &$flags, array &$reasons): int {
    $score = 0;
    foreach ($penalties as $penalty) {
        $pattern = $penalty['pattern'] ?? '';
        $pScore = (int)($penalty['score'] ?? 0);
        $flag = $penalty['flag'] ?? '';
        if ($pattern !== '' && @preg_match($pattern, $text)) {
            if (preg_match($pattern, $text)) {
                $score += $pScore;
                if ($flag !== '') {
                    $flags[] = $flag;
                }
                $reasons[] = ($flag !== '' ? $flag : 'penalty') . "({$pScore})";
            }
        }
    }
    return $score;
}

function determineStatus(float $score, array $thresholds): string {
    $ok = (float)($thresholds['ok'] ?? 70);
    $review = (float)($thresholds['review'] ?? 40);
    if ($score >= $ok) return 'ok';
    if ($score >= $review) return 'review';
    return 'needs-work';
}

$lines = file($input, FILE_IGNORE_NEW_LINES);
[$individuals, $families] = parseGedcom($lines);

$results = [];
foreach ($individuals as $person) {
    $name = displayName($person);
    $wikitreeId = $person['ids']['wikitree'] ?? '';
    $noteText = collectNoteText($person);
    $noteLength = strlen($noteText);
    $normalizedNote = normalizeText($noteText);

    $flags = [];
    $reasons = [];
    $score = 0;

    if (hasSection($noteText, 'Biography')) {
        $score += (int)$weights['hasBiography'];
        $reasons[] = 'has_bio(+'.$weights['hasBiography'].')';
    } else {
        $flags[] = 'missing_bio';
    }

    if (hasSection($noteText, 'Sources')) {
        $score += (int)$weights['hasSources'];
        $reasons[] = 'has_sources(+'.$weights['hasSources'].')';
    } else {
        $flags[] = 'missing_sources';
    }

    $refs = countRefs($noteText);
    if ($refs > 0) {
        $score += (int)$weights['hasReferences'];
        $reasons[] = 'has_refs(+'.$weights['hasReferences'].')';
    } else {
        $flags[] = 'no_refs';
    }

    $birth = $person['events']['BIRT'] ?? null;
    if ($birth && !empty($birth['date'])) {
        $score += (int)$weights['birthDate'];
        $reasons[] = 'birth_date(+'.$weights['birthDate'].')';
    } else {
        $flags[] = 'missing_birth_date';
    }

    if ($birth && !empty($birth['place'])) {
        $score += (int)$weights['birthPlace'];
        $reasons[] = 'birth_place(+'.$weights['birthPlace'].')';
    } else {
        $flags[] = 'missing_birth_place';
    }

    $death = $person['events']['DEAT'] ?? null;
    if ($death && !empty($death['date'])) {
        $score += (int)$weights['deathDate'];
        $reasons[] = 'death_date(+'.$weights['deathDate'].')';
    } else {
        $flags[] = 'missing_death_date';
    }

    if ($death && !empty($death['place'])) {
        $score += (int)$weights['deathPlace'];
        $reasons[] = 'death_place(+'.$weights['deathPlace'].')';
    } else {
        $flags[] = 'missing_death_place';
    }

    if (!empty($person['famc'])) {
        $score += (int)$weights['hasParents'];
        $reasons[] = 'has_parents(+'.$weights['hasParents'].')';
    } else {
        $flags[] = 'missing_parents';
    }

    if (!empty($person['fams'])) {
        $score += (int)$weights['hasSpouse'];
        $reasons[] = 'has_spouse(+'.$weights['hasSpouse'].')';
    } else {
        $flags[] = 'missing_spouse';
    }

    if (hasChildren($person, $families)) {
        $score += (int)$weights['hasChildren'];
        $reasons[] = 'has_children(+'.$weights['hasChildren'].')';
    } else {
        $flags[] = 'missing_children';
    }

    if (hasCategoriesOrTemplates($noteText)) {
        $score += (int)$weights['hasCategoriesOrTemplates'];
        $reasons[] = 'has_categories_or_templates(+'.$weights['hasCategoriesOrTemplates'].')';
    }

    $score += applyNoteLengthBonus($noteLength, $weights['noteLength'] ?? [], $reasons);

    $externalIdCount = 0;
    if (!empty($person['ids'])) {
        $externalIdCount = count($person['ids']);
        $extScore = min($externalIdCount * (int)$weights['externalId'], (int)$weights['externalIdMax']);
        if ($extScore > 0) {
            $score += $extScore;
            $reasons[] = "external_ids(+{$extScore})";
        }
    }

    $score += detectPenalties($normalizedNote, $penalties, $flags, $reasons);

    $status = determineStatus($score, $thresholds);

    $results[] = [
        'wikitreeId' => $wikitreeId !== '' ? $wikitreeId : null,
        'gedcomId' => $person['id'],
        'name' => $name,
        'score' => $score,
        'status' => $status,
        'noteLength' => $noteLength,
        'refs' => $refs,
        'externalIds' => $person['ids'],
        'flags' => array_values(array_unique($flags)),
        'reasons' => $reasons,
    ];
}

usort($results, function ($a, $b) use ($sortDir) {
    if ($a['score'] === $b['score']) return strcmp((string)$a['name'], (string)$b['name']);
    if ($sortDir === 'desc') return ($a['score'] < $b['score']) ? 1 : -1;
    return ($a['score'] < $b['score']) ? -1 : 1;
});

$filtered = [];
foreach ($results as $row) {
    if ($statusFilter !== '' && $row['status'] !== $statusFilter) {
        continue;
    }
    if ($minScore !== null && $row['score'] < $minScore) {
        continue;
    }
    $filtered[] = $row;
}

if ($topN > 0) {
    $filtered = array_slice($filtered, 0, $topN);
}

$summary = ['ok' => 0, 'review' => 0, 'needs-work' => 0];
foreach ($results as $row) {
    if (isset($summary[$row['status']])) $summary[$row['status']]++;
}

if ($outJson !== '') {
    $json = [
        'metadata' => [
            'generated' => date('c'),
            'input' => $input,
            'total' => count($results),
            'summary' => $summary,
        ],
        'people' => $filtered,
    ];
    if (@file_put_contents($outJson, json_encode($json, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) === false) {
        fwrite(STDERR, "Error: Failed to write JSON to {$outJson}\n");
        exit(2);
    }
    fwrite(STDOUT, "Wrote {$outJson}\n");
}

if ($outCsv !== '') {
    $fp = fopen($outCsv, 'w');
    if ($fp === false) {
        fwrite(STDERR, "Error: Failed to write CSV to {$outCsv}\n");
        exit(2);
    }
    fputcsv($fp, ['WikiTree ID', 'GEDCOM ID', 'Name', 'Score', 'Status', 'Note Length', 'Refs', 'Flags']);
    foreach ($filtered as $row) {
        fputcsv($fp, [
            $row['wikitreeId'] ?? '',
            $row['gedcomId'],
            $row['name'],
            $row['score'],
            $row['status'],
            $row['noteLength'],
            $row['refs'],
            implode(';', $row['flags']),
        ]);
    }
    fclose($fp);
    fwrite(STDOUT, "Wrote {$outCsv}\n");
}

if ($outMd !== '') {
    $lines = [];
    $lines[] = '# GEDCOM Biography Quality Report';
    $lines[] = '';
    $lines[] = '- Generated: ' . date('Y-m-d H:i:s');
    $lines[] = '- Input: ' . $input;
    $lines[] = '- Total: ' . count($results);
    $lines[] = '- Summary: ok=' . $summary['ok'] . ', review=' . $summary['review'] . ', needs-work=' . $summary['needs-work'];
    $lines[] = '';

    $lines[] = '## Results';
    $lines[] = '';
    $lines[] = '| Score | Status | WikiTree ID | Name | Flags |';
    $lines[] = '| --- | --- | --- | --- | --- |';
    foreach ($filtered as $row) {
        $lines[] = '| ' . $row['score'] . ' | ' . $row['status'] . ' | ' . ($row['wikitreeId'] ?? '') . ' | ' . $row['name'] . ' | ' . implode(', ', $row['flags']) . ' |';
    }

    if (@file_put_contents($outMd, implode("\n", $lines) . "\n") === false) {
        fwrite(STDERR, "Error: Failed to write Markdown to {$outMd}\n");
        exit(2);
    }
    fwrite(STDOUT, "Wrote {$outMd}\n");
}

if ($outJson === '' && $outMd === '' && $outCsv === '') {
    $sample = array_slice($filtered, 0, 10);
    foreach ($sample as $row) {
        $id = $row['wikitreeId'] ?? $row['gedcomId'];
        fwrite(STDOUT, sprintf("%6.1f  %-11s  %-18s  %s\n", $row['score'], $row['status'], $id, $row['name']));
    }
}

?>
